### ISSUE TITLE
kill mistakes

### ISSUE THREAD

**Issue by awdesch** [lborke/20150801-quantnet-MSM#3]
Please assigned existing sequences to all variables:

abline(v=median(rsn(x, xi=0, omega=1, alpha=-5))) 

Please change setup:

setwd(Sys.glob("~/downloads/")) # set your working directory

libraries = c("sn")
lapply(libraries, function(x) if (!(x %in% installed.packages())) {
  install.packages(x)
})
lapply(libraries, library, quietly = TRUE, character.only = TRUE)

Please change plot configurations:

pdf(name, width=12,height=4)
par(mfrow=c(1,3))

**Comment by SHIccc** [comment]
:memo: In addition, please remove the Unnecessary Codes. 
e.g. in the code of "MSMasprob.R"
-----------------
# install and load packages
libraries = c("")
lapply(libraries, function(x) if (!(x %in% installed.packages())) {
    install.packages(x)
})
lapply(libraries, library, quietly = TRUE, character.only = TRUE)
-----------------
