### ISSUE TITLE
Formatting question

### ISSUE THREAD

**Issue by ebommes** [lborke/20150801-quantnet-MSM#5]
I have one question:
Is e.g. `dnorm(seq(-4,4,0.2),0,1), col="blue"` correct according to our desired style or should it be `dnorm(seq(-4, 4, 0.2), 0, 1), col = "blue"` ?

Remarks:
Considering the Google style guide for R there should be a space after each comma.
Also, as far as I know WKH wants us to put spaces around every equal sign (even in functions).

**Comment by lborke** [comment]
Yes, there should be spaces between the characters etc.
Package formatR is doing that automatically.
